version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcelcom/json-api:v1-dev
    working_dir: /opt/json-api
    volumes:
      - .:/opt/json-api
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - composercache:/tmp
    user: ${CURRENT_UID}

volumes:
  composercache:
    driver: local
