version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcelcom/php:v1-dev
    working_dir: /opt/common
    environment:
      - COMPOSER_AUTH=$COMPOSER_AUTH
    volumes:
      - .:/opt/common
      - composercache:/tmp

volumes:
  composercache:
    driver: local
