version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcelcom/php:v2-dev
    working_dir: /opt/json-api
    volumes:
      - .:/opt/json-api
      - composercache:/tmp

volumes:
  composercache:
    driver: local
