version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcel.com/php:v1-dev
    working_dir: /opt/transformers
    environment:
    - COMPOSER_AUTH=$COMPOSER_AUTH
    volumes:
    - .:/opt/transformers
    - composercache:/tmp

volumes:
  composercache:
    driver: local
