version: 2
jobs:
  test:
    docker:
      - image: myparcelcom/php:7.2-cli
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            composer install
      - run:
          name: Run tests
          command: |
            vendor/bin/phpunit --no-coverage
