version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: |
            ./mp.sh setup

      - run:
          name: Run tests
          command: |
            ./mp.sh test
            if [ "$(head -n 3 build/report.junit.xml | grep 'errors="0"' | grep 'failures="0"')" == '' ]; then exit 1; else exit 0; fi
