name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.2

      - name: PHPUnit
        uses: php-actions/phpunit@v4
        with:
          version: 9
          php_version: 8.2
          configuration: phpunit.xml
